import mongoose from "mongoose";
import dotenv from "dotenv";
import InvestigationItem from "../models/InvestigationItem.js";

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || "mongodb://localhost:27017/hospital";

const VENDOR_CODE = "AROGYA";
const VENDOR_NAME = "AROGYA";

// category values match frontend INVESTIGATION_CATEGORIES constant
const LAB_ITEMS = [
  { slNo:   1, name: "ABSOLUTE EOSINOPHIL COUNT",                         category: "BLOOD",        labRate:   35, patientRate:  210 },
  { slNo:   2, name: "24 HRS URINE PROTEIN / CREATININE RATIO",           category: "URINE",        labRate:  200, patientRate:  650 },
  { slNo:   3, name: "ABSOLUTE BASOPHIL COUNT",                           category: "BLOOD",        labRate:   40, patientRate:  210 },
  { slNo:   4, name: "ABSOLUTE LYMPHOCYTE COUNT",                         category: "BLOOD",        labRate:   35, patientRate:  210 },
  { slNo:   5, name: "ABSOLUTE MONOCYTE COUNT",                           category: "BLOOD",        labRate:   40, patientRate:  210 },
  { slNo:   6, name: "ABSOLUTE NEUTROPHIL COUNT",                         category: "BLOOD",        labRate:   35, patientRate:  210 },
  { slNo:   7, name: "AFB STAIN / ZN STAIN",                              category: "MICROBIOLOGY", labRate:   50, patientRate:  450 },
  { slNo:   8, name: "ALBUMIN",                                           category: "BIOCHEMISTRY", labRate:   35, patientRate:  300 },
  { slNo:   9, name: "ALBUMIN : GLOBULIN",                                category: "BIOCHEMISTRY", labRate:   60, patientRate:  400 },
  { slNo:  10, name: "ALPHA FETO PROTEIN - AFP",                          category: "OTHER",        labRate:  340, patientRate: 1680 },
  { slNo:  11, name: "AMYLASE",                                           category: "BIOCHEMISTRY", labRate:   80, patientRate:  630 },
  { slNo:  12, name: "ANA (ANTI NUCLEAR ANTIBODY) HEP 2",                 category: "OTHER",        labRate:  650, patientRate: 1800 },
  { slNo:  13, name: "ANCA SERINE PROTEINASE 3 (C-ANCA)",                 category: "OTHER",        labRate:  850, patientRate:  300 },
  { slNo:  14, name: "ANTI CYCLIC CITRULLINATED PEPTIDE ANTIBODY (CCP)",  category: "OTHER",        labRate:  500, patientRate: 2100 },
  { slNo:  15, name: "ANTI DS DNA ANTIBODY",                              category: "OTHER",        labRate:  300, patientRate: 2340 },
  { slNo:  16, name: "ANTI MULLERIAN HORMONE - AMH",                      category: "OTHER",        labRate:  550, patientRate: 2640 },
  { slNo:  17, name: "ANTI NUCLEAR ANTIBODY (ANA)",                       category: "OTHER",        labRate:  300, patientRate: 1800 },
  { slNo:  18, name: "ANTI-THYROPEROXIDASE ANTIBODIES (ANTI-TPO)",        category: "OTHER",        labRate:  420, patientRate: 1400 },
  { slNo:  19, name: "APTT",                                              category: "BLOOD",        labRate:   80, patientRate:  720 },
  { slNo:  20, name: "ASO",                                               category: "OTHER",        labRate:  100, patientRate:  620 },
  { slNo:  21, name: "BETA HCG",                                          category: "OTHER",        labRate:  160, patientRate: 1440 },
  { slNo:  22, name: "BILIRUBIN (TOTAL + DIRECT + INDIRECT)",             category: "BIOCHEMISTRY", labRate:   60, patientRate:  420 },
  { slNo:  23, name: "BIOPSY",                                            category: "PATHOLOGY",    labRate:  150, patientRate:    0 },
  { slNo:  24, name: "BLEEDING TIME - BT",                                category: "BLOOD",        labRate:   10, patientRate:  110 },
  { slNo:  25, name: "BLOOD GROUPING",                                    category: "BLOOD",        labRate:   25, patientRate:  240 },
  { slNo:  26, name: "BLOOD UREA NITROGEN (BUN)",                         category: "BIOCHEMISTRY", labRate:  120, patientRate:  280 },
  { slNo:  27, name: "BLOOD UREA NITROGEN / CREATININE RATIO",            category: "BIOCHEMISTRY", labRate:  120, patientRate:  270 },
  { slNo:  28, name: "BT CT",                                             category: "BLOOD",        labRate:   20, patientRate:  220 },
  { slNo:  29, name: "CA-125 OVARIAN CANCER MARKER",                      category: "OTHER",        labRate:  280, patientRate: 1440 },
  { slNo:  30, name: "CA-19.9 PANCREATIC CANCER MARKER",                  category: "OTHER",        labRate:  280, patientRate: 2380 },
  { slNo:  31, name: "CALCIUM",                                           category: "BIOCHEMISTRY", labRate:   35, patientRate:  320 },
  { slNo:  32, name: "CARCINO EMBRYONIC ANTIGEN (CEA)",                   category: "OTHER",        labRate:  250, patientRate: 1380 },
  { slNo:  33, name: "CBC",                                               category: "BLOOD",        labRate:   50, patientRate:  420 },
  { slNo:  34, name: "CHLORIDE",                                          category: "BIOCHEMISTRY", labRate:   35, patientRate:  270 },
  { slNo:  35, name: "CHOLESTEROL",                                       category: "BIOCHEMISTRY", labRate:   50, patientRate:  280 },
  { slNo:  36, name: "CK NAC",                                            category: "CARDIOLOGY",   labRate:  150, patientRate:  900 },
  { slNo:  37, name: "CLOTTING TIME - CT",                                category: "BLOOD",        labRate:   10, patientRate:  110 },
  { slNo:  38, name: "COOMBS TEST - DIRECT",                              category: "BLOOD",        labRate:  180, patientRate:  600 },
  { slNo:  39, name: "COOMBS TEST - INDIRECT",                            category: "BLOOD",        labRate:  180, patientRate:  600 },
  { slNo:  40, name: "CPK - MB",                                          category: "CARDIOLOGY",   labRate:  150, patientRate:  900 },
  { slNo:  41, name: "CREATININE",                                        category: "BIOCHEMISTRY", labRate:   40, patientRate:  220 },
  { slNo:  42, name: "CRP",                                               category: "BIOCHEMISTRY", labRate:  100, patientRate:  630 },
  { slNo:  43, name: "CYTOLOGY FNAC",                                     category: "PATHOLOGY",    labRate:  300, patientRate: 1680 },
  { slNo:  44, name: "D-DIMER",                                           category: "BLOOD",        labRate:  450, patientRate: 1800 },
  { slNo:  45, name: "DEHYDROEPIANDROSTENEDIONE SULPHATE (DHEA-S)",       category: "OTHER",        labRate:  350, patientRate: 2000 },
  { slNo:  46, name: "DENGUE IgG",                                        category: "OTHER",        labRate:  200, patientRate:  950 },
  { slNo:  47, name: "DENGUE IgM",                                        category: "OTHER",        labRate:  200, patientRate:  950 },
  { slNo:  48, name: "DENGUE NS1",                                        category: "OTHER",        labRate:  200, patientRate: 1200 },
  { slNo:  49, name: "DENGUE SEROLOGY (NS1 IgG IgM)",                    category: "OTHER",        labRate:  600, patientRate: 3100 },
  { slNo:  50, name: "DIRECT BILIRUBIN",                                  category: "BIOCHEMISTRY", labRate:   35, patientRate:  280 },
  { slNo:  51, name: "DLC",                                               category: "BLOOD",        labRate:   20, patientRate:  180 },
  { slNo:  52, name: "ESR",                                               category: "BLOOD",        labRate:   15, patientRate:  180 },
  { slNo:  53, name: "ESTRADIOL (E2)",                                    category: "OTHER",        labRate:  200, patientRate:  700 },
  { slNo:  54, name: "EXFOLIATIVE CYTOLOGY (PAP) STAIN",                  category: "PATHOLOGY",    labRate:  200, patientRate:  950 },
  { slNo:  55, name: "FERRITIN",                                          category: "BIOCHEMISTRY", labRate:  175, patientRate:  940 },
  { slNo:  56, name: "FLUID FOR LDH",                                     category: "BIOCHEMISTRY", labRate:   80, patientRate:  640 },
  { slNo:  57, name: "FLUID RE/ME",                                       category: "OTHER",        labRate:  100, patientRate:  200 },
  { slNo:  58, name: "FOLATE",                                            category: "BIOCHEMISTRY", labRate:  450, patientRate: 1370 },
  { slNo:  59, name: "FREE THYROID PROFILE",                              category: "BIOCHEMISTRY", labRate:  250, patientRate: 1200 },
  { slNo:  60, name: "FSH",                                               category: "OTHER",        labRate:  110, patientRate:  880 },
  { slNo:  61, name: "FT3",                                               category: "BIOCHEMISTRY", labRate:   80, patientRate:  450 },
  { slNo:  62, name: "FT4",                                               category: "BIOCHEMISTRY", labRate:   80, patientRate:  450 },
  { slNo:  63, name: "G6PD",                                              category: "BLOOD",        labRate:  350, patientRate: 1440 },
  { slNo:  64, name: "GGT",                                               category: "BIOCHEMISTRY", labRate:   40, patientRate:  300 },
  { slNo:  65, name: "GLOBULIN",                                          category: "BIOCHEMISTRY", labRate:   35, patientRate:  280 },
  { slNo:  66, name: "GLOMERULAR FILTRATION RATE (eGFR)",                 category: "BIOCHEMISTRY", labRate:   60, patientRate:  720 },
  { slNo:  67, name: "GLUCOSE CHALLENGE TEST - GCT 75 GMS (PREGNANCY)",  category: "BIOCHEMISTRY", labRate:   75, patientRate:  250 },
  { slNo:  68, name: "GLUCOSE FASTING",                                   category: "BIOCHEMISTRY", labRate:   15, patientRate:  110 },
  { slNo:  69, name: "GLUCOSE PP",                                        category: "BIOCHEMISTRY", labRate:   15, patientRate:  110 },
  { slNo:  70, name: "GLUCOSE RANDOM",                                    category: "BIOCHEMISTRY", labRate:   15, patientRate:  110 },
  { slNo:  71, name: "GLUCOSE TOLERANCE TEST - GTT",                      category: "BIOCHEMISTRY", labRate:   45, patientRate:  330 },
  { slNo:  72, name: "GLUCOSE TOLERANCE TEST - GTT (5 SAMPLES)",         category: "BIOCHEMISTRY", labRate:   75, patientRate:  550 },
  { slNo:  73, name: "GRAM STAIN",                                        category: "MICROBIOLOGY", labRate:   50, patientRate:  450 },
  { slNo:  74, name: "HB ELECTROPHORESIS",                                category: "BLOOD",        labRate:  300, patientRate: 1600 },
  { slNo:  75, name: "HBA1C",                                             category: "BIOCHEMISTRY", labRate:  150, patientRate:  950 },
  { slNo:  76, name: "HBsAg (RAPID)",                                     category: "OTHER",        labRate:  100, patientRate:  800 },
  { slNo:  77, name: "HCV (RAPID)",                                       category: "OTHER",        labRate:  150, patientRate:  850 },
  { slNo:  78, name: "HDL",                                               category: "BIOCHEMISTRY", labRate:   70, patientRate:  350 },
  { slNo:  79, name: "HAEMOGLOBIN",                                       category: "BLOOD",        labRate:   20, patientRate:  180 },
  { slNo:  80, name: "HELICOBACTER PYLORI IgM",                           category: "OTHER",        labRate:  750, patientRate: 1600 },
  { slNo:  81, name: "HEPATITIS A VIRUS - IgG (HAV-IgG)",                 category: "OTHER",        labRate:  700, patientRate: 1800 },
  { slNo:  82, name: "HEPATITIS A VIRUS - IgM (HAV-IgM)",                 category: "OTHER",        labRate:  700, patientRate: 1800 },
  { slNo:  83, name: "HEPATITIS B SURFACE ANTIGEN (HBsAg) CLIA",          category: "OTHER",        labRate:  300, patientRate: 1000 },
  { slNo:  84, name: "HEPATITIS C VIRUS ANTIBODY (ANTI-HCV) CLIA",        category: "OTHER",        labRate:  300, patientRate: 1200 },
  { slNo:  85, name: "HEPATITIS E VIRUS - IgM (HEV-IgM)",                 category: "OTHER",        labRate:  700, patientRate: 1300 },
  { slNo:  86, name: "HERPES SIMPLEX VIRUS (HSV) 1 IgG",                  category: "OTHER",        labRate:  300, patientRate:  850 },
  { slNo:  87, name: "HERPES SIMPLEX VIRUS (HSV) 1 IgM",                  category: "OTHER",        labRate:  300, patientRate:  850 },
  { slNo:  88, name: "HERPES SIMPLEX VIRUS (HSV) 2 IgG",                  category: "OTHER",        labRate:  300, patientRate:  850 },
  { slNo:  89, name: "HERPES SIMPLEX VIRUS (HSV) 2 IgM",                  category: "OTHER",        labRate:  300, patientRate:  850 },
  { slNo:  90, name: "HIV (RAPID)",                                       category: "OTHER",        labRate:  150, patientRate:  950 },
  { slNo:  91, name: "HIV 1 AND 2 ANTIBODIES (ECLIA)",                    category: "OTHER",        labRate:  300, patientRate: 1250 },
  { slNo:  92, name: "HLA B 27 FLOW",                                     category: "OTHER",        labRate:  650, patientRate: 3700 },
  { slNo:  93, name: "HOMA",                                              category: "OTHER",        labRate:  600, patientRate: 1200 },
  { slNo:  94, name: "INSULIN FASTING",                                   category: "OTHER",        labRate:  250, patientRate:  900 },
  { slNo:  95, name: "INSULIN POST PRANDIAL",                             category: "OTHER",        labRate:  250, patientRate:  900 },
  { slNo:  96, name: "IRON",                                              category: "BIOCHEMISTRY", labRate:  120, patientRate:  750 },
  { slNo:  97, name: "IRON PROFILE",                                      category: "BIOCHEMISTRY", labRate:  450, patientRate: 4480 },
  { slNo:  98, name: "LDH",                                               category: "BIOCHEMISTRY", labRate:   80, patientRate:  640 },
  { slNo:  99, name: "LDL",                                               category: "BIOCHEMISTRY", labRate:   70, patientRate:  350 },
  { slNo: 100, name: "LFT",                                               category: "BIOCHEMISTRY", labRate:  100, patientRate:  720 },
  { slNo: 101, name: "LFT WITH GGT",                                      category: "BIOCHEMISTRY", labRate:  120, patientRate:  920 },
  { slNo: 102, name: "LH",                                                category: "OTHER",        labRate:  110, patientRate:  880 },
  { slNo: 103, name: "LIPASE",                                            category: "BIOCHEMISTRY", labRate:  100, patientRate:  630 },
  { slNo: 104, name: "LIPID PROFILE",                                     category: "BIOCHEMISTRY", labRate:  100, patientRate: 1020 },
  { slNo: 105, name: "LUPUS ANTICOAGULANT BY DRVVT",                      category: "OTHER",        labRate: 1000, patientRate: 3400 },
  { slNo: 106, name: "MAGNESIUM",                                         category: "BIOCHEMISTRY", labRate:  150, patientRate:  690 },
  { slNo: 107, name: "MALARIA DUAL ANTIGEN",                              category: "OTHER",        labRate:   50, patientRate:  700 },
  { slNo: 108, name: "MALIGNANT CELL",                                    category: "PATHOLOGY",    labRate:  250, patientRate: 1400 },
  { slNo: 109, name: "MATERNAL SCREENING DUAL MARKER",                    category: "OTHER",        labRate:  850, patientRate: 1800 },
  { slNo: 110, name: "MATERNAL SCREENING QUADRUPLE MARKER",               category: "OTHER",        labRate: 1100, patientRate: 3000 },
  { slNo: 111, name: "MATERNAL SCREENING TRIPLE MARKER",                  category: "OTHER",        labRate:  850, patientRate: 2250 },
  { slNo: 112, name: "MCH",                                               category: "BLOOD",        labRate:   20, patientRate:  180 },
  { slNo: 113, name: "MCHC",                                              category: "BLOOD",        labRate:   20, patientRate:  180 },
  { slNo: 114, name: "MCV",                                               category: "BLOOD",        labRate:   20, patientRate:  180 },
  { slNo: 115, name: "MEASLES (RUBELLA) ANTIBODY IgG",                    category: "OTHER",        labRate:  350, patientRate: 1500 },
  { slNo: 116, name: "MEASLES (RUBELLA) ANTIBODY IgM",                    category: "OTHER",        labRate:  350, patientRate: 1500 },
  { slNo: 117, name: "NT PRO BNP",                                        category: "CARDIOLOGY",   labRate: 1200, patientRate: 3360 },
  { slNo: 118, name: "P-ANCA",                                            category: "OTHER",        labRate: 1400, patientRate: 3000 },
  { slNo: 119, name: "PCV",                                               category: "BLOOD",        labRate:   20, patientRate:  180 },
  { slNo: 120, name: "PERIPHERAL SMEAR EXAMINATION",                      category: "BLOOD",        labRate:   50, patientRate:  180 },
  { slNo: 121, name: "PHOSPHORUS",                                        category: "BIOCHEMISTRY", labRate:   35, patientRate:  320 },
  { slNo: 122, name: "PLT COUNT",                                         category: "BLOOD",        labRate:   30, patientRate:  220 },
  { slNo: 123, name: "POTASSIUM",                                         category: "BIOCHEMISTRY", labRate:   35, patientRate:  260 },
  { slNo: 124, name: "PREGNANCY TEST",                                    category: "OTHER",        labRate:   30, patientRate:  350 },
  { slNo: 125, name: "PROCALCITONIN",                                     category: "OTHER",        labRate: 1200, patientRate: 3360 },
  { slNo: 126, name: "PROGESTERONE",                                      category: "OTHER",        labRate:  200, patientRate:  880 },
  { slNo: 127, name: "PROLACTIN",                                         category: "OTHER",        labRate:  110, patientRate:  880 },
  { slNo: 128, name: "PROTEIN ELECTROPHORESIS",                           category: "BIOCHEMISTRY", labRate:  450, patientRate: 1860 },
  { slNo: 129, name: "PSA (FREE)",                                        category: "OTHER",        labRate:  650, patientRate: 1800 },
  { slNo: 130, name: "PSA (TOTAL)",                                       category: "OTHER",        labRate:  150, patientRate:  950 },
  { slNo: 131, name: "PT - INR",                                          category: "BLOOD",        labRate:   80, patientRate:  720 },
  { slNo: 132, name: "PTH",                                               category: "BIOCHEMISTRY", labRate:  400, patientRate: 2550 },
  { slNo: 133, name: "PUS CS",                                            category: "MICROBIOLOGY", labRate:  150, patientRate:  760 },
  { slNo: 134, name: "RA FACTOR",                                         category: "OTHER",        labRate:  100, patientRate:  630 },
  { slNo: 135, name: "RBC COUNT",                                         category: "BLOOD",        labRate:   20, patientRate:  180 },
  { slNo: 136, name: "RETICULOCYTE COUNT",                                category: "BLOOD",        labRate:  100, patientRate:  360 },
  { slNo: 137, name: "RUBELLA (GERMAN MEASLES) ANTIBODY - IgG",           category: "OTHER",        labRate:  250, patientRate:  800 },
  { slNo: 138, name: "RUBELLA (GERMAN MEASLES) ANTIBODY - IgM",           category: "OTHER",        labRate:  250, patientRate:  800 },
  { slNo: 139, name: "SCRUB TYPHUS IgG (ELISA)",                          category: "OTHER",        labRate:  450, patientRate: 1800 },
  { slNo: 140, name: "SCRUB TYPHUS IgM (ELISA)",                          category: "OTHER",        labRate:  450, patientRate: 1800 },
  { slNo: 141, name: "SERUM ALLERGY TEST",                                category: "OTHER",        labRate: 1400, patientRate: 3360 },
  { slNo: 142, name: "SGOT / AST",                                        category: "BIOCHEMISTRY", labRate:   35, patientRate:  300 },
  { slNo: 143, name: "SGPT / ALT",                                        category: "BIOCHEMISTRY", labRate:   35, patientRate:  300 },
  { slNo: 144, name: "SMEAR FOR MALARIA PARASITE",                        category: "BLOOD",        labRate:   50, patientRate:  350 },
  { slNo: 145, name: "SODIUM",                                            category: "BIOCHEMISTRY", labRate:   35, patientRate:  260 },
  { slNo: 146, name: "SPUTUM AFB",                                        category: "MICROBIOLOGY", labRate:   50, patientRate:  450 },
  { slNo: 147, name: "SPUTUM CS",                                         category: "MICROBIOLOGY", labRate:  150, patientRate:  550 },
  { slNo: 148, name: "SPUTUM FOR MALIGNANT CELLS",                        category: "PATHOLOGY",    labRate:  250, patientRate: 1400 },
  { slNo: 149, name: "SPUTUM GRAM STAIN",                                 category: "MICROBIOLOGY", labRate:   50, patientRate:  450 },
  { slNo: 150, name: "STOOL CS",                                          category: "STOOL",        labRate:  150, patientRate:  550 },
  { slNo: 151, name: "STOOL FOR OCCULT BLOOD",                            category: "STOOL",        labRate:   50, patientRate:  280 },
  { slNo: 152, name: "STOOL ROUTINE",                                     category: "STOOL",        labRate:   50, patientRate:  150 },
  { slNo: 153, name: "T3",                                                category: "BIOCHEMISTRY", labRate:   50, patientRate:  450 },
  { slNo: 154, name: "T4",                                                category: "BIOCHEMISTRY", labRate:   50, patientRate:  450 },
  { slNo: 155, name: "TB GOLD GAMMA INTERFERON",                          category: "MICROBIOLOGY", labRate: 1300, patientRate: 2800 },
  { slNo: 156, name: "TESTOSTERONE FREE",                                 category: "OTHER",        labRate:  500, patientRate: 1100 },
  { slNo: 157, name: "TESTOSTERONE TOTAL",                                category: "OTHER",        labRate:  180, patientRate:  800 },
  { slNo: 158, name: "THYROID PROFILE",                                   category: "BIOCHEMISTRY", labRate:  150, patientRate: 1350 },
  { slNo: 159, name: "TIBC",                                              category: "BIOCHEMISTRY", labRate:  165, patientRate: 1110 },
  { slNo: 160, name: "TLC",                                               category: "BLOOD",        labRate:   20, patientRate:  180 },
  { slNo: 161, name: "TOTAL BETA HCG",                                    category: "OTHER",        labRate:  160, patientRate: 1440 },
  { slNo: 162, name: "TOTAL BILIRUBIN",                                   category: "BIOCHEMISTRY", labRate:   35, patientRate:  300 },
  { slNo: 163, name: "TOTAL IgE (ECLIA)",                                 category: "OTHER",        labRate:  180, patientRate: 1800 },
  { slNo: 164, name: "TOTAL PROTEIN",                                     category: "BIOCHEMISTRY", labRate:   35, patientRate:  280 },
  { slNo: 165, name: "TOXOPLASMA IgG",                                    category: "OTHER",        labRate:  450, patientRate: 1550 },
  { slNo: 166, name: "TOXOPLASMA IgM",                                    category: "OTHER",        labRate:  450, patientRate: 1550 },
  { slNo: 167, name: "TRANSFERIN",                                        category: "BIOCHEMISTRY", labRate:  300, patientRate: 1680 },
  { slNo: 168, name: "TRIGLYCERIDE",                                      category: "BIOCHEMISTRY", labRate:   50, patientRate:  280 },
  { slNo: 169, name: "TROP I",                                            category: "CARDIOLOGY",   labRate:  400, patientRate: 1600 },
  { slNo: 170, name: "TROP T",                                            category: "CARDIOLOGY",   labRate:  500, patientRate: 1600 },
  { slNo: 171, name: "TSH",                                               category: "BIOCHEMISTRY", labRate:   50, patientRate:  450 },
  { slNo: 172, name: "TYPHI DOT",                                         category: "OTHER",        labRate:  120, patientRate:  800 },
  { slNo: 173, name: "UREA",                                              category: "BIOCHEMISTRY", labRate:   40, patientRate:  220 },
  { slNo: 174, name: "URIC ACID",                                         category: "BIOCHEMISTRY", labRate:   40, patientRate:  250 },
  { slNo: 175, name: "URINE ACR",                                         category: "URINE",        labRate:  120, patientRate:  760 },
  { slNo: 176, name: "URINE BILE PIGMENT",                                category: "URINE",        labRate:   40, patientRate:  150 },
  { slNo: 177, name: "URINE BILE SALT",                                   category: "URINE",        labRate:   40, patientRate:  150 },
  { slNo: 178, name: "URINE CHLORIDE",                                    category: "URINE",        labRate:   45, patientRate:  280 },
  { slNo: 179, name: "URINE CS",                                          category: "URINE",        labRate:  150, patientRate:  450 },
  { slNo: 180, name: "URINE GLUCOSE",                                     category: "URINE",        labRate:   40, patientRate:  150 },
  { slNo: 181, name: "URINE KETONE BODY",                                 category: "URINE",        labRate:   40, patientRate:  300 },
  { slNo: 182, name: "URINE MICROALBUMIN",                                category: "URINE",        labRate:  120, patientRate:  760 },
  { slNo: 183, name: "URINE MICROPROTEIN",                                category: "URINE",        labRate:  150, patientRate:  800 },
  { slNo: 184, name: "URINE POTASSIUM",                                   category: "URINE",        labRate:   45, patientRate:  280 },
  { slNo: 185, name: "URINE PROTEIN",                                     category: "URINE",        labRate:   40, patientRate:  150 },
  { slNo: 186, name: "URINE PROTEIN 24 HRS",                              category: "URINE",        labRate:  165, patientRate:  800 },
  { slNo: 187, name: "URINE ROUTINE",                                     category: "URINE",        labRate:   35, patientRate:  150 },
  { slNo: 188, name: "URINE SODIUM",                                      category: "URINE",        labRate:   45, patientRate:  280 },
  { slNo: 189, name: "VDRL (RAPID)",                                      category: "OTHER",        labRate:   80, patientRate:  400 },
  { slNo: 190, name: "VDRL RAPID PLASMA REAGIN",                          category: "OTHER",        labRate:   80, patientRate:  400 },
  { slNo: 191, name: "VIT B12",                                           category: "BIOCHEMISTRY", labRate:  250, patientRate: 1190 },
  { slNo: 192, name: "VITAMIN D",                                         category: "BIOCHEMISTRY", labRate:  250, patientRate: 1200 },
  { slNo: 193, name: "VITAMIN D (CLIA)",                                  category: "BIOCHEMISTRY", labRate:  300, patientRate: 1500 },
  { slNo: 194, name: "VLDL",                                              category: "BIOCHEMISTRY", labRate:   50, patientRate:  280 },
  { slNo: 195, name: "WIDAL",                                             category: "OTHER",        labRate:   40, patientRate:  460 },
];

const XRAY_ITEMS = [
  { slNo: 196, name: "X-RAY ABDOMEN ERECT/SUPINE/LAT",   category: "RADIOLOGY", labRate: 0, patientRate:  250 },
  { slNo: 197, name: "X-RAY CERVICAL SPINE AP/LAT",       category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 198, name: "X-RAY HAND AP/LAT",                 category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 199, name: "X-RAY WRIST AP/LAT/OBL",            category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 200, name: "X-RAY FOREARM AP/LAT",              category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 201, name: "X-RAY HUMERUS AP/LAT",              category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 202, name: "X-RAY SHOULDER AP & LAT",           category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 203, name: "X-RAY CLAVICLE AP",                 category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 204, name: "X-RAY PELVIS AP",                   category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 205, name: "X-RAY FEMUR AP/LAT",                category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 206, name: "X-RAY KNEE JOINT AP/LAT",           category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 207, name: "X-RAY LEG AP/LAT",                  category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 208, name: "X-RAY ANKLE AP/LAT",                category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 209, name: "X-RAY FOOT AP/LAT",                 category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 210, name: "X-RAY HEEL AP/LAT",                 category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 211, name: "X-RAY SKULL AP/LAT",                category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 212, name: "X-RAY DORSAL SPINE AP/LAT",         category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 213, name: "X-RAY LUMBER SPINE AP/LAT",         category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 214, name: "X-RAY HIP JOINT AP/LAT",            category: "RADIOLOGY", labRate: 0, patientRate:  360 },
  { slNo: 215, name: "BARIUM SWALLOW",                    category: "RADIOLOGY", labRate: 0, patientRate:  900 },
  { slNo: 216, name: "BARIUM ENEMA",                      category: "RADIOLOGY", labRate: 0, patientRate: 2250 },
  { slNo: 217, name: "BMFT",                              category: "RADIOLOGY", labRate: 0, patientRate: 2250 },
  { slNo: 218, name: "IVP / IVU",                         category: "RADIOLOGY", labRate: 0, patientRate: 1350 },
  { slNo: 219, name: "HSG",                               category: "RADIOLOGY", labRate: 0, patientRate: 2700 },
  { slNo: 220, name: "ASU",                               category: "RADIOLOGY", labRate: 0, patientRate: 1400 },
  { slNo: 221, name: "MCU",                               category: "RADIOLOGY", labRate: 0, patientRate: 1700 },
  { slNo: 222, name: "X-RAY KUB",                         category: "RADIOLOGY", labRate: 0, patientRate:  440 },
  { slNo: 223, name: "X-RAY COCCYX AP/LAT",              category: "RADIOLOGY", labRate: 0, patientRate:  440 },
  { slNo: 224, name: "DORSO-LUMBER AP/LAT",               category: "RADIOLOGY", labRate: 0, patientRate:  900 },
  { slNo: 225, name: "X-RAY CHEST AP/PA/LAT/OBL",         category: "RADIOLOGY", labRate: 0, patientRate:  250 },
];

const ALL_ITEMS = [...LAB_ITEMS, ...XRAY_ITEMS];

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log("Connected to MongoDB");

  let inserted = 0;
  let skipped  = 0;

  for (const item of ALL_ITEMS) {
    const existing = await InvestigationItem.findOne({ vendorCode: VENDOR_CODE, name: item.name });
    if (existing) {
      skipped++;
      continue;
    }
    await InvestigationItem.create({
      ...item,
      vendorCode: VENDOR_CODE,
      vendorName: VENDOR_NAME,
      isActive: true,
    });
    console.log(`  ✓ [${item.category.padEnd(12)}] ${item.name}`);
    inserted++;
  }

  console.log(`\nDone. Inserted: ${inserted}  Skipped (already exist): ${skipped}`);
  await mongoose.disconnect();
}

seed().catch(err => {
  console.error(err);
  process.exit(1);
});
